name: Deploy to Railway

on: [push, pull_request]

jobs:

  package:
    name: Maven Package (no tests) 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 11
        uses: actions/setup-java@v3.5.1
        with:
          java-version: 11
      - name: Maven Package
        run: mvn -B clean package -DskipTests
